# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Combined input matrix (C++ implementation)
#' 
#' @param X A numeric matrix (N x M) where rows are judges and columns are objects
#' @param Wk Optional numeric vector of weights for each ranking
#' @return The M x M combined input matrix
#' @keywords internal
combinpmatr_impl <- function(X, Wk = NULL) {
    .Call(`_ConsRank_combinpmatr_impl`, X, Wk)
}

#' Find branches for Branch-and-Bound (C++ implementation - FIXED)
#' 
#' @param R Current ranking MATRIX (1 row)
#' @param ord Order vector (indices, 1-based)
#' @param b Subset of positions (1-based)
#' @param FULL Logical, if TRUE use full rankings (step=2)
#' @return Matrix of candidate rankings
#' @keywords internal
findbranches_impl <- function(R, ord, b, FULL) {
    .Call(`_ConsRank_findbranches_impl`, R, ord, b, FULL)
}

#' Kemeny design matrix (C++ implementation)
NULL

kemenydesign_cpp <- function(X) {
    .Call(`_ConsRank_kemenydesign_cpp`, X)
}

kemenydesign_impl <- function(X) {
    .Call(`_ConsRank_kemenydesign_impl`, X)
}

#' Batch computation of PenaltyBB2 for multiple candidates (C++ implementation - FIXED)
NULL

PenaltyBB2_batch_impl <- function(cij, candidates, ord) {
    .Call(`_ConsRank_PenaltyBB2_batch_impl`, cij, candidates, ord)
}

#' Penalty calculation for Branch-and-Bound algorithm (C++ implementation)
NULL

PenaltyBB2_impl <- function(cij, candidate, ord) {
    .Call(`_ConsRank_PenaltyBB2_impl`, cij, candidate, ord)
}

scorematrix_impl <- function(x) {
    .Call(`_ConsRank_scorematrix_impl`, x)
}

#' Reordering for Branch-and-Bound algorithm (C++ implementation)
NULL

ReorderingBB_impl <- function(RR) {
    .Call(`_ConsRank_ReorderingBB_impl`, RR)
}

#' Score matrix calculation (C++ implementation)
NULL

scorematrix_cpp <- function(X) {
    .Call(`_ConsRank_scorematrix_cpp`, X)
}

